"""About / colophon page — an honest, concrete account of the engine.

Single measured column of prose (~70ch), mono section overlines reusing the
shared .sec-head device, and one signature touch: the bracket slot grammar set
as a monospace specimen block. The long-form body is wrapped in data-no-i18n so
the pt-BR DOM-walker skips it (the page chrome still translates); every technical
claim here is true of the current code — see the modules it names.
"""
from __future__ import annotations

from ..shell import shell

# The slot-grammar specimen: real tokens from the openfootball feed, each with a
# plain-language gloss. This is the page's one signature block — a mono ledger of
# the grammar that wc/bracket.py's resolve_slot() turns into teams or candidate
# sets. Kept factual: these token shapes are exactly the ones the regexes match.
_TOKENS = [
    ("1C", "Winner of Group C"),
    ("2F", "Runner-up of Group F"),
    ("3A/B/C/D", "A third-placed team — from Group A, B, C or D"),
    ("W76", "Winner of match 76"),
    ("L101", "Loser of match 101 — into the third-place match"),
]


def _specimen():
    rows = "".join(
        f'<div class="ab-tok"><code class="ab-tok-k">{tok}</code>'
        f'<span class="ab-tok-v">{gloss}</span></div>'
        for tok, gloss in _TOKENS
    )
    return (
        '<figure class="ab-specimen" aria-label="Slot grammar tokens">'
        '<figcaption class="ab-spec-cap">Feed tokens → teams or candidate sets</figcaption>'
        f'<div class="ab-tok-grid">{rows}</div>'
        '</figure>'
    )


def _sec(num, title, *paras, extra=""):
    head = (f'<div class="sec-head ab-head"><h2>{title}</h2>'
            f'<span class="muted">&#167;{num}</span></div>')
    body = "".join(f"<p>{p}</p>" for p in paras)
    return f'<section class="ab-sec">{head}{body}{extra}</section>'


def page_about(ctx):
    body = f"""
<article class="about" data-no-i18n>
  <header class="ab-hero">
    <p class="ab-over">Colophon</p>
    <h1 class="ab-title">How this site is built</h1>
    <p class="ab-lede">A self-updating World Cup hub — live scores, honest
      probabilities, a connected bracket, a play-money pool, in English and
      Brazilian Portuguese — generated by a pure-standard-library Python engine
      and served as flat files. This is the honest account of the engineering
      underneath, and none of it is visible from the front page.</p>
  </header>

{_sec("01", "What this is",
  "This site tracks all 104 matches of the 2026 World Cup — 48 teams, 12 groups, "
  "and the knockouts through to the final at MetLife Stadium on July&nbsp;19. Star "
  "any team and it lights up everywhere: its group table, its live chance of "
  "reaching the knockouts, and its projected road through the bracket. Around that "
  "sits a fully connected knockout tree, a fill-it-yourself fantasy bracket, a "
  "play-money betting pool, and a day-by-day calendar you can subscribe to as "
  ".ics. Every number is derived from the live results feed — nothing is typed in "
  "by hand. The whole thing is bilingual, with a client-side English / "
  "Brazilian-Portuguese toggle, and it re-publishes itself within about five "
  "minutes of a result landing.")}

{_sec("02", "The engine",
  "The site is a static-site generator written in pure Python — standard library "
  "only. No framework, no bundler, no third-party packages at build time, and "
  "zero runtime dependencies. One render pass turns a single JSON feed into over "
  "120 files: an HTML page for each of the 48 team hubs and 12 groups plus the "
  "home, bracket, fantasy, bets and calendar views; 49 subscribable .ics calendar "
  "feeds; one stylesheet; the client script; and the SVG art. The code is small, "
  "focused modules — feed fetch and cache, standings math, bracket resolution, "
  "timezone handling, shared HTML-fragment builders, and one module per page. "
  "Nothing runs on a server to render a page. The output is flat files a CDN "
  "serves directly.")}

{_sec("03", "The slot grammar",
  "The openfootball feed doesn't name knockout participants until they're known — "
  "it encodes each as a <b>slot token</b>. A group finish like <code>1C</code> "
  "(Group&nbsp;C winner) or <code>3A/B/C/D</code> (one third-placed team), or a "
  "match edge like <code>W76</code> (winner of match&nbsp;76). One resolver, "
  "<code>resolve_slot()</code> in <code>wc/bracket.py</code>, turns each token "
  "into either a decided nation or the set of teams still able to fill it. That "
  "single abstraction powers the bracket connectors, every team's road, the "
  "calendar's &ldquo;3&nbsp;possible&rdquo; cells, the fantasy picker's options, "
  "and the betting board — all reading the same resolved slots. As results land, "
  "tokens resolve to nations automatically; nothing is ever hand-edited.",
  extra=_specimen())}

{_sec("04", "Honest probabilities",
  "Two different questions, two different methods. For &ldquo;will they reach the "
  "knockouts?&rdquo; the engine runs a <b>seeded 20,000-iteration Monte-Carlo</b>: "
  "it simulates every remaining group match with plausible scorelines, ranks all "
  "twelve groups, then takes the eight best third-placed teams — exactly the real "
  "qualification rule, cross-group thirds and all. The seed is fixed, so identical "
  "data yields identical published percentages. For &ldquo;have they "
  "clinched?&rdquo; it doesn't sample — it <b>enumerates</b>. With <i>n</i> group "
  "games left it walks all 3<sup><i>n</i></sup> win/draw/loss combinations and "
  "shows a clinch-or-eliminated badge only when it holds in every single one. A "
  "badge is a proof, not a forecast.")}

{_sec("05", "Determinism as deploy control",
  "The build is deterministic by contract: identical input data produces "
  "byte-identical output. The daily job leans on that. A GitHub Action polls the "
  "results feed every five minutes through the match window, but rewrites the "
  "cached feed and its timestamp <b>only when something actually changed</b> — so "
  "an unchanged poll regenerates the exact same bytes, produces no git diff, and "
  "triggers no deploy. Each real result is therefore exactly one Cloudflare Pages "
  "deploy, keeping the tournament far under the free tier's 500-a-month. "
  "Determinism is tested, too: five real tournament snapshots lifted from this "
  "repo's own git history — early groups, the thirds race, groups complete, "
  "mid-knockout with penalty shootouts, and today — get rebuilt and hash-compared, "
  "so any silent change to output is caught.")}

{_sec("06", "The live layer",
  "openfootball posts a result at full time, which is perfect for standings but "
  "blind during a match. So a thin Cloudflare Pages Function proxies ESPN's public "
  "scoreboard and returns a small normalized JSON the page polls for in-progress "
  "scores, edge-cached about 25 seconds so a crowd can't multiply upstream calls. "
  "The polling is <b>kickoff-aware</b>: each match carries its kickoff instant, and "
  "the client sleeps until just before the next one rather than hammering the "
  "endpoint all day. It's pure progressive enhancement — the static page already "
  "shows every kickoff time and every final score, so if the proxy is unreachable "
  "nothing breaks and live scores simply don't appear. Name reconciliation "
  "(USA&nbsp;&harr;&nbsp;United&nbsp;States) happens client-side to keep the proxy "
  "a thin pass-through.")}

{_sec("07", "The betting pool",
  "The play-money pool is a real backend on a static site: a Cloudflare D1 "
  "(SQLite) database and a handful of Functions. Everyone starts with $100 and "
  "bets on knockout winners at odds snapshotted the moment the bet is placed. The "
  "money handling is written to survive concurrent requests. Stakes are debited "
  "with a <b>guarded conditional write</b> — subtracted only if the balance still "
  "covers them — so two simultaneous bets can't both overdraw. Cancellations "
  "delete-then-refund using SQL <code>RETURNING</code>, so a concurrent edit can't "
  "over-refund. Settlement runs on every page load and is idempotent and atomic: "
  "winners are credited exactly once inside a single transaction. Identity is "
  "deliberately passwordless — a display name plus a shared pool code is the whole "
  "credential, a stated friends-only, not-real-money tradeoff.")}

{_sec("08", "Bilingual AI editorial",
  "Each team's &ldquo;road to the final&rdquo; blurb is written by Claude — a short "
  "sports-desk paragraph recapping the last match and framing the next — then "
  "translated into Brazilian Portuguese by a second Claude pass. Neither runs at "
  "build time. Both are cached and keyed by a <b>fingerprint</b>: a SHA-256 of the "
  "exact facts that shaped the prompt (the opponent, the round, the kickoff, the "
  "candidate pool). When a result moves a team's situation its fingerprint changes "
  "and only that one blurb regenerates; everything else is untouched. The "
  "Portuguese cache is stamped with the English blurb's fingerprint, and the page "
  "serves a translation only while those fingerprints still match — so a stale "
  "translation can never publish. It silently falls back to English instead.")}

  <section class="ab-sec ab-colophon">
    <div class="sec-head ab-head"><h2>Colophon</h2><span class="muted">&#167;09</span></div>
    <dl class="ab-cl">
      <div class="ab-cl-row"><dt>Stack</dt><dd>Python&nbsp;3.12 (standard library) generating
        static HTML, CSS and vanilla JavaScript; hosted on Cloudflare&nbsp;Pages with Pages
        Functions and a D1 database. No framework, no bundler, no CSS or JS dependencies.</dd></div>
      <div class="ab-cl-row"><dt>Data</dt><dd>Match results from openfootball/worldcup.json
        (public domain); betting odds from The&nbsp;Odds&nbsp;API, de-vigged and folded into
        two-way prices; live in-match scores proxied from ESPN's public scoreboard.</dd></div>
      <div class="ab-cl-row"><dt>Editorial</dt><dd>Road-to-the-final blurbs and their pt-BR
        translations written by Claude (Anthropic), cached and fingerprinted.</dd></div>
      <div class="ab-cl-row"><dt>Type &amp; art</dt><dd>System neo-grotesque and monospace
        faces; original SVG marks; a self-hosted flag webfont is the only asset fetched over
        the wire, so Windows renders flag emoji instead of two-letter codes.</dd></div>
      <div class="ab-cl-row"><dt>Design</dt><dd>&ldquo;Broadcast Ink&rdquo; — newsprint paper,
        near-black ink, one vermilion accent, tracked mono labels, hard edges.</dd></div>
      <div class="ab-cl-row"><dt>Source</dt><dd><a class="ab-lnk"
        href="https://github.com/scottdflorida/worldcup2026" target="_blank"
        rel="noopener">github.com/scottdflorida/worldcup2026</a></dd></div>
      <div class="ab-cl-row"><dt>Built by</dt><dd>Scott Florida.</dd></div>
    </dl>
  </section>
</article>
"""
    return shell(
        "About — World Cup 2026", "about.html", body, ctx,
        desc="How the World Cup 2026 tracker is built — a pure-standard-library Python "
             "static-site generator, the slot grammar behind the bracket, seeded "
             "Monte-Carlo probabilities, deterministic deploys, and a play-money betting backend.",
        page="about.html",
        crumb=[("Home", "index.html"), ("About this site", None)],
    )
